export const translate = {
  ru: {
    Search: "Поиск",
    add: "Добавить +",
    deleteAll: "Удалить все",
    MAX: "Макс.:",
    MIN: "Мин.:",
    currentCity: "Текущее местоположение",
    feels: "По ощущениям как:",
    hourlyTitle: "ПОЧАСОВОЙ ПРОГНОЗ",
    airQuality: "КАЧЕСТВО ВОЗДУХА",
    noLabel: "Нет данных",
    veryGood: "Отличное",
    good: "Хорошее",
    notGood: "Удовлетворительное",
    bad: "Плохое",
    veryBad: "Очень плохое",
    clearAir: "Воздух чистый, без вреда для здоровья",
    goodQuality: "Качество хорошее, безопасно для всех",
    easeBadAir: "Лёгкое раздражение у чувствительных",
    badAir: "Вредно для людей с заболеваниями",
    dangerous: "Опасно для здоровья, избегать улицы",
    today: "Сегодня",
    dailyTitle: "ПРОГНОЗ НА 10 ДНЕЙ",
    feelsLike: "ОЩУЩАЕТСЯ КАК",
    fackt: "Фактически:",
    veryCold: "Очень холодно",
    cold: "Прохладно",
    comfort: "Комфортно",
    warm: "Тепло",
    hot: "Жарко",
    humidity: "ВЛАЖНОСТЬ",
    devPoint: "Точка росы:",
    pressure: "ДАВЛЕНИЕ",
    Gpa: "гПа",
    up: "Восход",
    down: "Закат",
    meters: "м",
    kilomiters: "км",
    visibility: "ВИДИМОСТЬ",
    veryGoodVisibility: "Идеальная видимость",
    goodVisibility: "Хорошая видимость",
    mediumVisibility: "Средняя видимость",
    badVisibility: "Плохая видимость",
    wind: "ВЕТЕР",
    speed: "км/ч",
    gusts: "Порывы",
    deg: "Направление",
    s: "С",
    sv: "СВ",
    v: "В",
    uv: "ЮВ",
    u: "Ю",
    uz: "ЮЗ",
    z: "З",
    sz: "СЗ",
    Not: "Неизвестно",
    weekdays: ["Вс", "Пн", "Вт", "Ср", "Чт", "Пт", "Сб"],
  },
  ua: {
    Search: "Пошук",
    add: "Додати +",
    deleteAll: "Видалити все",
    MAX: "Макс.:",
    MIN: "Мін.:",
    currentCity: "Поточне місце",
    feels: "Відчувається як:",
    hourlyTitle: "ПОГОДА ПО ГОДИНАХ",
    airQuality: "ЯКІСТЬ ПОВІТРЯ",
    noLabel: "Немає даних",
    veryGood: "Відмінна",
    good: "Хороша",
    notGood: "Задовільна",
    bad: "Погана",
    veryBad: "Дуже погана",
    clearAir: "Повітря чисте, безпечно для здоров'я",
    goodQuality: "Якість хороша, безпечно для всіх",
    easeBadAir: "Можливе легке подразнення у чутливих людей",
    badAir: "Шкідливо для людей із захворюваннями",
    dangerous: "Небезпечно для здоров’я, уникайте вулиці",
    today: "Сьогодні",
    dailyTitle: "ПРОГНОЗ НА 10 ДНІВ",
    feelsLike: "ВІДЧУВАЄТЬСЯ ЯК",
    fackt: "Фактично:",
    veryCold: "Дуже холодно",
    cold: "Прохолодно",
    comfort: "Комфортно",
    warm: "Тепло",
    hot: "Жарко",
    humidity: "ВОЛОГІСТЬ",
    devPoint: "Точка роси:",
    pressure: "ТИСНЯВИЙ",
    Gpa: "гПа",
    up: "Схід",
    down: "Захід",
    meters: "м",
    kilomiters: "км",
    visibility: "ВИДИМІСТЬ",
    veryGoodVisibility: "Ідеальна видимість",
    goodVisibility: "Хороша видимість",
    mediumVisibility: "Середня видимість",
    badVisibility: "Погана видимість",
    wind: "ВІТЕР",
    speed: "км/год",
    gusts: "Пориви",
    deg: "Напрямок",
    s: "Пн",
    sv: "ПнСх",
    v: "Сх",
    uv: "ПдСх",
    u: "Пд",
    uz: "ПдЗх",
    z: "Зх",
    sz: "ПнЗх",
    Not: "Невідомо",
    weekdays: ["Нд", "Пн", "Вт", "Ср", "Чт", "Пт", "Сб"],
  },
  cz: {
    Search: "Hledat",
    add: "Přidat +",
    deleteAll: "Smazat vše",
    MAX: "Max.:",
    MIN: "Min.:",
    currentCity: "Aktuální poloha",
    feels: "Pocitově:",
    hourlyTitle: "HODINOVÁ PŘEDPOVĚĎ",
    airQuality: "KVALITA OVZDUŠÍ",
    noLabel: "Žádná data",
    veryGood: "Výborná",
    good: "Dobrá",
    notGood: "Uspokojivá",
    bad: "Špatná",
    veryBad: "Velmi špatná",
    clearAir: "Čistý vzduch, bez zdravotního rizika",
    goodQuality: "Dobrá kvalita, bezpečné pro všechny",
    easeBadAir: "Mírné podráždění pro citlivé osoby",
    badAir: "Škodlivé pro osoby s nemocemi",
    dangerous: "Nebezpečné pro zdraví, vyhýbejte se venku",
    today: "Dnes",
    dailyTitle: "PŘEDPOVĚĎ NA 10 DNÍ",
    feelsLike: "POCITOVĚ",
    fackt: "Skutečně:",
    veryCold: "Velmi chladno",
    cold: "Chladno",
    comfort: "Příjemně",
    warm: "Teplo",
    hot: "Horko",
    humidity: "VLHKOST",
    devPoint: "Rosný bod:",
    pressure: "TLAK",
    Gpa: "hPa",
    up: "Východ",
    down: "Západ",
    meters: "m",
    kilomiters: "km",
    visibility: "VIDITELNOST",
    veryGoodVisibility: "Perfektní viditelnost",
    goodVisibility: "Dobrá viditelnost",
    mediumVisibility: "Střední viditelnost",
    badVisibility: "Špatná viditelnost",
    wind: "VÍTR",
    speed: "km/h",
    gusts: "Nárazy",
    deg: "Směr",
    s: "S",
    sv: "SV",
    v: "V",
    uv: "JV",
    u: "J",
    uz: "JZ",
    z: "Z",
    sz: "SZ",
    Not: "Neznámé",
    weekdays: ["Ne", "Po", "Út", "St", "Čt", "Pá", "So"],
  },
  en: {
    Search: "Search",
    add: "Add +",
    deleteAll: "Delete all",
    MAX: "Max:",
    MIN: "Min:",
    currentCity: "Current location",
    feels: "Feels like:",
    hourlyTitle: "HOURLY FORECAST",
    airQuality: "AIR QUALITY",
    noLabel: "No data",
    veryGood: "Excellent",
    good: "Good",
    notGood: "Moderate",
    bad: "Poor",
    veryBad: "Very Poor",
    clearAir: "Clean air, no health risk",
    goodQuality: "Good quality, safe for everyone",
    easeBadAir: "Slight irritation for sensitive people",
    badAir: "Harmful for people with conditions",
    dangerous: "Dangerous, avoid going outside",
    today: "Today",
    dailyTitle: "10-DAY FORECAST",
    feelsLike: "FEELS LIKE",
    fackt: "Actual:",
    veryCold: "Very cold",
    cold: "Cool",
    comfort: "Comfortable",
    warm: "Warm",
    hot: "Hot",
    humidity: "HUMIDITY",
    devPoint: "Dew point:",
    pressure: "PRESSURE",
    Gpa: "hPa",
    up: "Sunrise",
    down: "Sunset",
    meters: "m",
    kilomiters: "km",
    visibility: "VISIBILITY",
    veryGoodVisibility: "Perfect visibility",
    goodVisibility: "Good visibility",
    mediumVisibility: "Moderate visibility",
    badVisibility: "Poor visibility",
    wind: "WIND",
    speed: "km/h",
    gusts: "Gusts",
    deg: "Direction",
    s: "N",
    sv: "NE",
    v: "E",
    uv: "SE",
    u: "S",
    uz: "SW",
    z: "W",
    sz: "NW",
    Not: "Unknown",
    weekdays: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
  },
};
